name = input("Enter your name, adventurer: ")
print("I like your name, "+name)
age = input("And how old are you? ")
print(age+", what a fine age, indeed! Like a well aged wine!")
print("One more question, my kind adventurer,")
color = input("What is your favorite color? ")
print("Oh, I do so hate the color "+color+", but I suppose that is just my personal opinion.")
